### ISSUE TITLE
Unexpected behaviour when Providing state

### ISSUE THREAD

**Issue by bradlc** [valotas/preact-context#12]
Hi. I’m trying to update context from a nested component, similar to [this example in the React docs](https://reactjs.org/docs/context.html#updating-context-from-a-nested-component).

However, `preact-context` doesn’t behave as expected (and as `React.createContext` does).

Here’s an example:
`preact-context`: https://codesandbox.io/s/q3n91mr3nw
`React.createContext`: https://codesandbox.io/s/nrpx565z50

**Comment by valotas** [comment]
Hi Brad,

I'll have a look at it as soon as I'll be back from my holidays

Cheers,
George

**Comment by bradlc** [comment]
Hey George,

Sounds good, thanks! 😎

Had a quick look, and if I change the `Consumer` component's `shouldComponentUpdate` method to just `return true;` it works as expected. So maybe it's an issue with the condition here?:

https://github.com/valotas/preact-context/blob/74217c0ee6ba9a725cafb026356260bceb7c3df5/src/context.ts#L85-L88

**Comment by bradlc** [comment]
Actually, although changing it to `return true;` fixes the test case above, it doesn’t fix the original issue that I’m having on a project (again, it works fine with `React.createContext`). I will create another reduced test case for that if I can.

Edit: the issue on my project was actually caused by [this preact bug](https://github.com/developit/preact/issues/853), so you can disregard this comment

**Comment by valotas** [comment]
@bradlc the problem is that preact mutates the state instance on each update hence the `this.state.value !== nextState.value` check is always true. You have to make sure that you pass a new instance of the value to the Context.Provider (ex: `<Context.Provider value={{ ...this.state }}>`, see [your updated example](https://codesandbox.io/s/2jw7639n40)).

**Comment by valotas** [comment]
I'll try to catch up with some of the `preact` maintainers in order to provide a proper solution for that as it looks like it will be a problem that many preact users might have.

**Comment by marvinhagemeister** [comment]
This issue is caused by using an older release of `preact`. With the most recent version `8.3.1` I can't reproduce the issue anymore and the example works exactly the same as for `react`.

**Comment by bradlc** [comment]
You’re right, updating the CodeSandbox to `8.3.1` fixes the issue. Thanks!

**Comment by valotas** [comment]
thanks a lot for the clarification @marvinhagemeister !
