### ISSUE TITLE
Tyepscript Issue with provider value

### ISSUE THREAD

**Issue by gilnoy** [valotas/preact-context#16]
Hi,

I'm using preact with typescript and i'm getting this message whenever i wanna pass object to the provider value "[ts] Type '{ test: string; }' is not assignable to type 'string'.

context.d.ts(4, 5): The expected type comes from property 'value' which is declared here on type 'Readonly<ProviderProps<string> & Attributes & { children?: string | number | object | VNode<any> | ComponentChild[] | null | undefined; ref?: Ref<any> | undefined; }>'

By definition i can only pass a string ?

Thanks

Gil

**Comment by valotas** [comment]
Hi @gilnoycloudinary 

Based on the typescript definition, you should pass to the Provider a value with the shape that you define when you create the context:

```typescript
type MyContext = {
  test: string
};
const ctx = createContext<MyContext>( { test: "default value" });
``` 

Then you can use:

```typescript
const someValue: MyContext = { test: "new value" };
return <ctx.Provider value={someValue} />
```

Unfortunately I can not guess anything more from the provided error.

**Comment by gilnoy** [comment]
Thanks, got it!
