### ISSUE TITLE
Uncaught ReferenceError: preact is not defined

### ISSUE THREAD

**Issue by dackom** [valotas/preact-context#7]
Hello, I decided to try this with latest preact 8.2.9 but I got this in console log:

<img width="593" alt="screen shot 2018-05-25 at 14 55 48" src="https://user-images.githubusercontent.com/11218933/40545342-c6eaee62-602b-11e8-8623-81211b67c7e7.png">

Any ideas?

**Comment by valotas** [comment]
Could you please try again with `v1.0.1`

4d6a69365f978fc80d7df7c51a23a86e7c253b4e should fix this

**Comment by dackom** [comment]
Yes, it's working now. Thank you.
